#!/bin/bash
clear
lan="\033[36m"
huang="\033[33m"
function logo(){
echo -e "$lan
                             _    
                            | |
                   __      _| |__  _   _
                   \ \ /\ / / '_ \| | | |
                    \ V  V /| | | | |_| |
                     \_/\_/ |_| |_|\__, |
                                    __/ |
                                   |___/'
"
}
function main(){
echo -e "$huang
----------------------------------------------------------------
[1]切换国内软件源                           [2]安装ohmyzsh
[3]修复termux新版的一排键盘                 [4]退出程序
[5]安装命令行版百度网盘                     [6]美化vim(spacevim)
[7]安装各种python工具                       [8]好玩的东西
[9]安装基本工具
----------------------------------------------------------------
"
read -p "请输入序号:" xuan
	case $xuan in
1)
	clear
	echo "更新软件包"
	echo "deb https://mirrors.tuna.tsinghua.edu.cn/termux/ stable main">/data/data/com.termux/files/usr/etc/apt/sources.list
	rm -rf /data/data/com.termux/files/usr/etc/apt/sources.list.d
	echo -e "$lan完成"
	main
	;;
2)
	pkg in curl -y >/dev/null
	sh -c "$(curl -fsSL https://github.com/Cabbagec/termux-ohmyzsh/raw/master/install.sh)"
	main
	;;
3)
  cd ~
  if test -d .termux
  then 
    cd 
  else
	mkdir $HONE/.termux
  fi
	echo "extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]" >> $HOME/.termux/termux.properties
	echo "请重启termux"
	main
	;;
4)
	exit
	;;
5)
	echo "deb [trusted=yes] http://termux.iikira.com stable main" >> /data/data/com.termux/files/usr/etc/apt/sources.list
	echo 安装中
	pkg in baidupcs-go -y >/dev/null 2>&1
	BaiduPCS-Go config set -appid 266719
	echo 安装完成，开启请使用BaiduPCS-Go命令启动
	;;
6)
  curl -sLf https://spacevim.org/cn/install.sh | bash
  echo "下次启动vim自动安装！"
  ;;
7)
  py
  ;;
8)
  van
  ;;
9)
  cd ~
  pkg in tar unzip python git wget curl -y >log.txt
  echo "安装完成，日志输出到log.txt"
  echo "配置pip..."
  if test -d .pip
  then 
    cd 
  else
    mkdir .pip
  fi
  echo "
[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
[install]
trusted-host = https://pypi.tuna.tsinghua.edu.cn
"> ~/.pip/pip.conf
  main
  ;;
*)
	echo "请输入正确的序号！"
	main
esac
}
function van(){
clear
logo
echo -e "$huang
[100]游戏-sl跑火车      [101]atilo安装linux
[105]cmatrix仿黑客帝国  [102]返回
[104]nyancat彩虹猫      [106]月球探索车
"
read -p "请输入序号:" vang
case $vang in
100)
  pkg in sl -y
  sl 
  van
  ;;
101)

  ;;
102)
  clear 
  logo
  main
  ;;
104)
  pkg in nyancat -y
  nyancat
  ;;
105)
  pkg in cmatrix -y
  cmatrix
  ;;
106)
  pkg in moon-buggy -y
  moon-buggy
  ;;
*)
  echo "请输入正确的序号！"
  van
  ;;
esac
}
function py(){
clear
logo
echo -e "$huang 
[500]返回          [501]you-get
"
read -p "请输入序号:" pyg
case $pyg in
500)
  clear
  logo
  main
  ;;
501)
  pip install you-get
  ;;
esac
}
logo
main
